instadoc/main/urls.py
from django.conf.urls import patterns, url
from .views import Index


urlpatterns = patterns(
    '',
    url(r'^$', Index.as_view(), name="index"),
    url(r'^(?P<category>.*)/$', Index.as_view(), name="category"),
)

instadoc/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from api import v1_api


urlpatterns = patterns(
    '',
    url(r'^api/', include(v1_api.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('instadoc.main.urls', namespace="main")),
)

instadoc/main/models.py
from django.db import models


class Documentation(models.Model):
    item = models.CharField(max_length=254)
    url = models.CharField(max_length=254)
    html = models.TextField(blank=True)
    category = models.ForeignKey("Category", related_name="docs")

    class Meta:
        ordering = ('-item',)

    def __unicode__(self):
        return self.item


class Category(models.Model):
    item = models.CharField(max_length=254)
    url = models.CharField(max_length=254, blank=True)

    class Meta:
        ordering = ('item',)

    def __unicode__(self):
        return self.item

instadoc/main/views.py
from django.template import RequestContext
from django.views.generic.base import TemplateView
from django.shortcuts import get_object_or_404

from redis import Redis
redis = Redis(host='redis', port=6379)


from models import Category


class Index(TemplateView):
    template_name = 'main/index.html'

    def get(self, request, category=None):
        tmpl = RequestContext(request)
        tmpl["categories"] = Category.objects.all()
        tmpl["selected_category"] = get_object_or_404(Category, item='python')
        if category:
            tmpl["selected_category"] = get_object_or_404(Category, item=category.lower())

        # hits
        tmpl["counter"] = redis.incr('hits_per_category_{}'.format(tmpl["selected_category"].pk))
        return self.render_to_response(tmpl)

instadoc/main/templates/base.html
<!DOCTYPE html>
<html ng-app="instadocApp">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title> InstaDoc </title>
        <meta name="keywords" content="instadoc, python, jquery, css, html, javascript, documentation" />
        <meta name="description" content="get python/css/html ... documentation really fast" />

        {% block css %}
            <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}/css/bootstrap.css" />
            <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}/css/base.css" />
        {% endblock %}

        <link rel="shortcut icon" href="{{ STATIC_URL }}/images/favicon.ico" />
        {% block extrahead %}{% endblock %}
    </head>

    <body ng-controller="instadocAppCtrl" class="ng-cloak">
        <!-- Header -->
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    {% block header %}
                        <a class="brand" href="{% url 'main:index' %}">InstaDoc <span class="small-text">0.1dev</span></a>
                    {% endblock %}
                </div>
            </div>
            <a href="https://github.com/chassing/instadoc" target="_blank">
                <img class="fork-me-at-github" src="{{ STATIC_URL }}/images/forkme_right_darkblue_121621.png" alt="Fork me on GitHub" />
            </a>
        </div>

        <!-- Container -->
        <div class="{% block container_class %}container{% endblock %}">
            {% block main %}{% endblock %}
        </div>

        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        {% block js %}
            <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
            <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.min.js"></script>
            <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular-sanitize.js"></script>
            <script src="{{ STATIC_URL }}/js/tasty-resource.js"></script>
            <script src="{{ STATIC_URL }}/js/instadoc.js"></script>
        {% endblock %}
    </body>
</html>

instadoc/main/templates/main/index.html
{% extends "base.html" %}

{% block extrahead %}
    <script type="text/javascript">
        API_URL = "{% url 'api_dispatch_list' api_name='v1' resource_name='documentation' %}";
        CATEGORY_ID = "{{ selected_category.id }}";
    </script>
{% endblock %}

{% block header %}
    {{ block.super }}
    <ul class="nav">
        {% for category in categories %}
            <li {% if category == selected_category %} class="active" {% endif %}>
                <a href="{% url 'main:category' category=category.item %}">{{ category.item|title }} {% if category == selected_category %} ({{ counter }}) {% endif %}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

{% block main %}
    <div class="row">
        {% verbatim %}
            <div id='sidebar' class="well span3">
                <input ng-model="search_item" placeholder="search ..." autofocus="true">

                <p ng-repeat="documentation in documentations | filter:search_item" class="permalink" ng-click="load_documentation(documentation.id)">
                    {{ documentation.item }}
                </p>
            </div>

            <div id='detail' class="span8" style="margin-top: 10px" ng-bind-html="item_doc.html">

            </div>
        {% endverbatim %}
    </div>
{% endblock %}